name: when_to_leave
channels:
  - defaults
dependencies:
  - anyio=4.7.0
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cloudpickle=3.0.0
  - comm=0.2.1
  - cyrus-sasl=2.1.28
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.7.1
  - farama-notifications=0.0.4
  - freetype=2.13.3
  - gettext=0.21.0
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.28.1
  - icu=73.1
  - idna=3.7
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.5
  - jax-jumpy=1.0.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - krb5=1.20.1
  - libabseil=20250127.0
  - libcurl=8.12.1
  - libcxx=14.0.6
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libiconv=1.16
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libxml2=2.13.8
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mistune=3.1.2
  - mysql=8.4.0
  - narwhals=1.31.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openldap=2.6.4
  - openssl=3.0.16
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.8.0
  - pip=25.1
  - platformdirs=4.3.7
  - plotly=6.0.1
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.19.1
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qtbase=6.7.3
  - qtconsole=5.6.1
  - qtdeclarative=6.7.3
  - qtpy=2.4.1
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - scipy=1.15.3
  - send2trash=1.8.2
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.17.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tornado=6.5
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - dill==0.4.0
      - filelock==3.18.0
      - fonttools==4.58.0
      - fsspec==2025.5.1
      - gymnasium==1.1.1
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - pandarallel==1.6.5
      - pillow==11.2.1
      - pyparsing==3.2.3
      - stable-baselines3==2.6.0
      - sympy==1.14.0
      - torch==2.7.0
prefix: /Users/preetkaria/miniconda3/envs/when_to_leave
